name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-2019
    
    steps:
    - uses: actions/checkout@v2
    - uses: actions/checkout@v2
    - name: Checkout submodules
      shell: bash
      run: |
        git submodule sync --recursive
        git -c protocol.version=2 submodule update --init --force --recursive --depth=1
    - name: install
      run: npm install
    - name: make
      run: npm run build
